name: setup
description: Collection of widgets, tools, and other useful pieces when beginning a new project
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_sheet_localization: ^2.0.1
  freezed_annotation: ^0.12.0
  get: ^3.23.1
  get_storage: ^1.3.2
  remote_state: ^1.5.0

dev_dependencies:
  build_runner: ^1.10.13
  freezed: ^0.12.7


flutter:
  uses-material-design: true
